// Sheet 02 — Signal Dictionary v1. All 13 signal codes.
// Decay schedules from Sheet 04 Section 3.

export type SignalDef = {
  code: string;
  signalName: string;
  label: string;
  category: "structural" | "assortment" | "demand" | "vendor_openness";
  type: "event" | "trend";
  defaultWeight: number;
  weightMin: number;
  weightMax: number;
  examplePhrases: string[];
  guardrailNotes: string;
  decayRule: { schedule: { upToDays: number; multiplier: number }[] };
  programRelevance: string;
  maxOccurrences: number | null;
  occurrenceWindowDays: number | null;
};

const STRUCTURAL_DECAY = {
  schedule: [
    { upToDays: 14, multiplier: 1.0 },
    { upToDays: 30, multiplier: 0.7 },
    { upToDays: 60, multiplier: 0.5 },
    { upToDays: 90, multiplier: 0.25 },
    { upToDays: 365, multiplier: 0.0 },
  ],
};

const ASSORTMENT_EVENT_DECAY = {
  schedule: [
    { upToDays: 14, multiplier: 1.0 },
    { upToDays: 30, multiplier: 0.8 },
    { upToDays: 60, multiplier: 0.5 },
    { upToDays: 90, multiplier: 0.25 },
    { upToDays: 180, multiplier: 0.0 },
  ],
};

const ASSORTMENT_TREND_DECAY = {
  schedule: [
    { upToDays: 14, multiplier: 1.0 },
    { upToDays: 30, multiplier: 0.75 },
    { upToDays: 60, multiplier: 0.5 },
    { upToDays: 90, multiplier: 0.0 },
  ],
};

const DEMAND_TREND_DECAY = {
  schedule: [
    { upToDays: 14, multiplier: 1.0 },
    { upToDays: 30, multiplier: 0.5 },
    { upToDays: 60, multiplier: 0.0 },
  ],
};

const VENDOR_DECAY = {
  schedule: [
    { upToDays: 14, multiplier: 1.0 },
    { upToDays: 30, multiplier: 0.6 },
    { upToDays: 60, multiplier: 0.3 },
    { upToDays: 90, multiplier: 0.0 },
  ],
};

export const SIGNALS: SignalDef[] = [
  {
    code: "S1",
    signalName: "store_expansion_announced",
    label: "Store Expansion / New Location",
    category: "structural",
    type: "event",
    defaultWeight: 30,
    weightMin: 25,
    weightMax: 35,
    examplePhrases: [
      "opening our second location",
      "new store coming",
      "now open in",
      "second location",
      "expanding our flagship",
      "new branch opening",
      "pop-up opening",
    ],
    guardrailNotes:
      "Very strong. Single event sufficient if score >= 60. Do not combine with generic announcements.",
    decayRule: STRUCTURAL_DECAY,
    programRelevance: "All programs. Highest priority for Everyday Essentials + Stackable Rings.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "S2",
    signalName: "store_renovation",
    label: "Store Renovation / Redesign",
    category: "structural",
    type: "event",
    defaultWeight: 25,
    weightMin: 20,
    weightMax: 30,
    examplePhrases: [
      "closed for renovations",
      "store refresh",
      "new look coming soon",
      "reopening soon",
      "remodel",
      "store redesign",
      "case reset",
    ],
    guardrailNotes:
      "Followed by case reset. Combine with A2/A3 for cluster. Alone = monitor.",
    decayRule: STRUCTURAL_DECAY,
    programRelevance: "Case reset = assortment review. Pitch Stackable Rings + Everyday Essentials.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "S3",
    signalName: "ownership_change",
    label: "New Owner / Leadership Change",
    category: "structural",
    type: "event",
    defaultWeight: 30,
    weightMin: 25,
    weightMax: 35,
    examplePhrases: [
      "under new ownership",
      "after 30 years",
      "new management",
      "proudly under new ownership",
      "passing the torch",
      "next generation",
      "new chapter",
      "acquired by",
    ],
    guardrailNotes: "New leadership reviews all vendors. One of strongest purchase intent signals.",
    decayRule: STRUCTURAL_DECAY,
    programRelevance: "All programs. New owner likely reviewing full assortment.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "S4",
    signalName: "buyer_hiring",
    label: "Hiring Buyer / Merchandiser",
    category: "structural",
    type: "event",
    defaultWeight: 25,
    weightMin: 20,
    weightMax: 30,
    examplePhrases: [
      "hiring a jewelry buyer",
      "seeking experienced merchandiser",
      "inventory manager needed",
      "buyer position open",
      "category lead hiring",
      "we're hiring a buyer",
    ],
    guardrailNotes: "Preparation for assortment change. Combine with LinkedIn job posting confirmation.",
    decayRule: STRUCTURAL_DECAY,
    programRelevance: "All programs. Preparing for new vendor additions.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "A1",
    signalName: "new_brand_added",
    label: "New Brand / Designer Added",
    category: "assortment",
    type: "event",
    defaultWeight: 25,
    weightMin: 20,
    weightMax: 30,
    examplePhrases: [
      "now carrying",
      "welcome to our family",
      "excited to introduce",
      "new designer",
      "newest addition to our",
      "introducing",
    ],
    guardrailNotes: "Shows active vendor rotation. High value if brand is in similar price tier.",
    decayRule: ASSORTMENT_EVENT_DECAY,
    programRelevance: "Capsule Collection Launch. Shows buying receptivity.",
    maxOccurrences: 2,
    occurrenceWindowDays: 90,
  },
  {
    code: "A2",
    signalName: "category_expansion",
    label: "Category Expansion",
    category: "assortment",
    type: "event",
    defaultWeight: 25,
    weightMin: 20,
    weightMax: 25,
    examplePhrases: [
      "expanding our men's section",
      "new stackable ring bar",
      "more everyday gold",
      "adding a layering wall",
      "now offering bridal",
      "introducing our",
      "new category",
    ],
    guardrailNotes: "Match to relevant program. Check which category before routing.",
    decayRule: ASSORTMENT_EVENT_DECAY,
    programRelevance: "Program match = expanding category. Stackables, Men's, Bridal Add-On.",
    maxOccurrences: 2,
    occurrenceWindowDays: null,
  },
  {
    code: "A3",
    signalName: "website_category_change",
    label: "Website Nav / Category Restructure",
    category: "assortment",
    type: "event",
    defaultWeight: 20,
    weightMin: 15,
    weightMax: 25,
    examplePhrases: ["stacks", "layers", "everyday gold", "men's", "bridal", "personalized"],
    guardrailNotes:
      "Detectable via website scrape diff. Confirm with Instagram posts. Alone = moderate signal.",
    decayRule: { schedule: [
      { upToDays: 30, multiplier: 1.0 },
      { upToDays: 60, multiplier: 0.8 },
      { upToDays: 120, multiplier: 0.5 },
      { upToDays: 180, multiplier: 0.25 },
      { upToDays: 365, multiplier: 0.0 },
    ] },
    programRelevance: "Category-specific programs. Strong corroboration for A2.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "A4",
    signalName: "category_promotion_trend",
    label: "Repeated Category Promotion",
    category: "assortment",
    type: "trend",
    defaultWeight: 6,
    weightMin: 5,
    weightMax: 8,
    examplePhrases: [
      "stackable rings",
      "ear stacks",
      "layered necklaces",
      "everyday gold",
      "ring stack",
      "necklace layering",
    ],
    guardrailNotes:
      "Trend signal. Cap at 3 occurrences per 60-day window. Alone scores max 18. Needs S or V to push above 40.",
    decayRule: ASSORTMENT_TREND_DECAY,
    programRelevance: "Promoted category = program target. High relevance to Chroma Core / Everyday Essentials.",
    maxOccurrences: 3,
    occurrenceWindowDays: 60,
  },
  {
    code: "D1",
    signalName: "customer_questions_category",
    label: "Customer Inquiry Pattern",
    category: "demand",
    type: "trend",
    defaultWeight: 5,
    weightMin: 4,
    weightMax: 7,
    examplePhrases: [
      "price?",
      "available in gold?",
      "do you have these in studs?",
      "size options?",
      "do you ship?",
      "any in 14k?",
    ],
    guardrailNotes:
      "Demand exceeding current depth. Requires 3+ comments on same product type. Do not score generic comments.",
    decayRule: DEMAND_TREND_DECAY,
    programRelevance: "Category-specific. ODM/private label fit. Personalization programs.",
    maxOccurrences: 3,
    occurrenceWindowDays: 30,
  },
  {
    code: "D2",
    signalName: "customization_demand",
    label: "Customization / Personalization Demand",
    category: "demand",
    type: "trend",
    defaultWeight: 5,
    weightMin: 4,
    weightMax: 6,
    examplePhrases: [
      "design your own",
      "custom name necklace",
      "personalized jewelry",
      "can I get this engraved",
      "custom order",
      "make to order",
    ],
    guardrailNotes: "ODM/private label fit. Do not upweight generic 'customize' language.",
    decayRule: DEMAND_TREND_DECAY,
    programRelevance: "ODM Capsule, Private Label, Personalization Program.",
    maxOccurrences: 3,
    occurrenceWindowDays: 30,
  },
  {
    code: "D3",
    signalName: "category_sold_out_often",
    label: "Repeated Stockouts in Category",
    category: "demand",
    type: "trend",
    defaultWeight: 7,
    weightMin: 5,
    weightMax: 9,
    examplePhrases: [
      "sold out again",
      "back soon",
      "waiting list",
      "out of stock",
      "restocking",
      "selling fast",
    ],
    guardrailNotes:
      "GUARDRAIL: Standalone D3 score capped at 10. Cannot promote tier alone. Needs structural or vendor corroboration.",
    decayRule: DEMAND_TREND_DECAY,
    programRelevance: "Everyday Essentials (volume), Quick-Turn Reorder Program.",
    maxOccurrences: 2,
    occurrenceWindowDays: 30,
  },
  {
    code: "V1",
    signalName: "seeking_new_designers",
    label: "Actively Seeking New Lines",
    category: "vendor_openness",
    type: "event",
    defaultWeight: 35,
    weightMin: 30,
    weightMax: 40,
    examplePhrases: [
      "tag your favorite designers",
      "looking for new jewelry lines to carry",
      "what brands should I carry",
      "open to new vendors",
      "seeking new lines",
      "vendor recommendations",
    ],
    guardrailNotes:
      "Strongest single signal. Near buying stage. Single V1 can trigger outreach queue if score >= 60.",
    decayRule: VENDOR_DECAY,
    programRelevance: "All programs. First-contact opportunity. Immediate outreach candidate.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "V2",
    signalName: "private_label_inquiry",
    label: "Private Label / ODM Inquiry",
    category: "vendor_openness",
    type: "event",
    defaultWeight: 35,
    weightMin: 30,
    weightMax: 40,
    examplePhrases: [
      "interested in a house collection",
      "do you offer private label",
      "looking for a manufacturing partner",
      "ODM capability",
      "white label jewelry",
      "private label program",
    ],
    guardrailNotes: "Extremely high value. ODM/private label ideal fit. Single V2 + S or A = immediate outreach.",
    decayRule: VENDOR_DECAY,
    programRelevance: "Capsule Collection Launch, ODM Custom Program.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
  {
    code: "V3",
    signalName: "category_program_inquiry",
    label: "Category Program Inquiry",
    category: "vendor_openness",
    type: "event",
    defaultWeight: 35,
    weightMin: 30,
    weightMax: 40,
    examplePhrases: [
      "do you have a stud program",
      "looking for a hoop assortment",
      "need a stackable ring program",
      "any open-to-buy programs",
      "memo program",
      "consignment program",
    ],
    guardrailNotes: "Treat as immediate outreach candidate. Specific program language = near-decision stage.",
    decayRule: VENDOR_DECAY,
    programRelevance: "Exact program match to inquiry. Direct pitch opportunity.",
    maxOccurrences: 1,
    occurrenceWindowDays: null,
  },
];
